spring.application.name=demo

# MySQL Connection Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cinema_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG

# Spring Mail Properties
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:buiviet300304@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ampv fiis pzdb wozf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPAY Configuration
vnp.tmncode=${VNP_TMNCODE:ORX5X3G0}
vnp.hashsecret=${VNP_HASHSECRET:Z3B1BDC29C1BJGZM6EZ5CNM4KZR2W1LW}
vnp.payurl=${VNP_PAYURL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnp.returnurl=${VNP_RETURNURL:http://localhost:8080/api/invoices/vnpay-callback}

# MOMO Configuration
momo.payurl=${MOMO_PAYURL:https://test-payment.momo.vn/web/index.99f86f8b.js}
momo.returnurl=${MOMO_RETURNURL:http://localhost:8080/api/invoices/momo-callback}
momo.notifyurl=${MOMO_NOTIFYURL:http://localhost:8080/api/invoices/momo-notify}
momo.accesskey=${MOMO_ACCESSKEY:F8590EC0C6CB49FBBEBA3B3C49910418}
momo.secretkey=${MOMO_SECRETKEY:K951B6PE1waDMi640xQKMv7DlH7oH885}
momo.partnercode=${MOMO_PARTNERCODE:MOMO}

# App Frontend URL (used for payment redirect callback)
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

