spring.application.name=demo

# MySQL Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG

# Spring Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buiviet300304@gmail.com
spring.mail.password=ampv fiis pzdb wozf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPAY Configuration
vnp.tmncode=ORX5X3G0
vnp.hashsecret=Z3B1BDC29C1BJGZM6EZ5CNM4KZR2W1LW
vnp.payurl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.returnurl=http://localhost:8080/api/invoices/vnpay-callback
